### ISSUE TITLE
Limits at 115WPM

### ISSUE THREAD

**Issue by snootysteppes** [robbiebusinessacc/slowPaste#2]
is this an issue with your program? I don't think it is as i made my own version and was also limited to 115WPM. how can this be counteracted?

**Comment by robbiebusinessacc** [comment]
The issue isn't specific to your program but rather a result of random delays and system limitations. The random delay adds variability, which increases the total time and caps the speed. Other factors like Python's timing precision and library overhead also contribute. To counteract this, reduce or remove the random delay, optimize the typing method, and use more precise timers for better performance.
